name: CI/CD Docker - Mi Primera Automatización

# ¿Cuándo se activa esto?
on:
  push:
    branches: [ "main" ] # Se activa cada vez que haces push a la rama 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub nos presta una máquina virtual Linux gratis

    steps:
      # 1. Descarga tu código del repositorio a la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Se conecta a Docker Hub usando las llaves que guardaste en "Secrets"
      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Configura el motor avanzado de Docker (Buildx)
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Construye la imagen y la sube (Push)
      - name: Construir y subir imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Aquí se forma el nombre final: usuario/repo:versión
          tags: ${{ secrets.DOCKER_USERNAME }}/mi-primera-imagen:latest
